accounts/urls.py
from django.urls import path 
from . import views

urlpatterns = [ 
    path('account/<slug:slug>', views.account, name='account'),
    path('user-login/', views.user_login, name='user-login'),
    path('user-logout/', views.user_logout, name='user-logout'),
    path('user-signup/', views.user_signup, name='user-signup'),
    path('notifications/', views.user_notifications, name='notifications'),
    path('update-profile/', views.update_profile, name='update-profile'),
    path('user-settings/', views.user_settings, name='user-settings'),
    path('update-inbox-settings/', views.update_inbox_settings, name='update-inbox-settings'),
    path('change-password', views.change_password, name='change-password'),
    path('change-display-photo/', views.change_display_photo, name='change-display-photo'),
]

app/urls.py
from django.urls import path 
from . import views

urlpatterns = [ 
    path('', views.home, name='home'),
    path('offers/', views.offers, name='offers'),
    path('create-offer/', views.create_offer, name='create-offer'),
    path('view-offer/<slug:slug>', views.view_offer, name='view-offer'),
    path('delete-offer/<slug:slug>', views.delete_offer, name='delete-offer'),
    path('edit-offer/<slug:slug>', views.edit_offer, name='edit-offer'),
    path('enquire/<slug:slug>', views.enquire, name='enquire'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse

class CustomUser(AbstractUser):
    location = models.CharField(max_length=30)
    about = models.TextField(max_length=500, null=True, blank=True)
    phone_number = models.CharField(max_length=10, null=True, blank=True)
    shortlist = models.ManyToManyField('app.Offer',related_name='shortlisted', blank=True)
    enquired = models.ManyToManyField('app.Offer', related_name='enquiries' ,blank=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    display_photo = models.ImageField(default='default.jpg', blank=True)

    account_type_choices = (
        ('NU', 'Normal User'),
        ('DA', 'Dealership Account'),
    )
    account_type = models.CharField(max_length=2, choices=account_type_choices)
    
    notification_inbox_choices = (
        ('E', 'Email'),
        ('S', 'SMS'),
        ('B', 'Both')
    )
    notification_inbox = models.CharField(max_length=1, choices=notification_inbox_choices, default='E', blank=True)

    def __str__(self) -> str:
        return self.username
    
    def get_absolute_url(self):
        return reverse('account', kwargs={'slug': self.slug})
 
class Notification(models.Model):
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=40)
    body = models.TextField(max_length=1000)
    view_count = models.IntegerField(default=0, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    icon_choices = (
        ('E', 'bi bi-envelope'),
        ('I', 'bi bi-info-circle'),
        ('ET', 'bi bi-exclamation-triangle'),
        ('S', 'bi bi-star'),
    )
    icon = models.CharField(max_length=2, choices=icon_choices)

    class Meta:
        ordering = ['-date']

    def __str__(self) -> str:
        return self.title

app/models.py
from django.db import models
from django.urls import reverse
 
class Offer(models.Model):
    owner = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE, blank=True, null=True)
    vehicle_name = models.CharField(max_length=30)
    location = models.CharField(max_length=30)
    price = models.IntegerField()
    mileage = models.IntegerField()
    
    vehicle_type_choices = (
        ('L', 'Light motor vehicle'),
        ('H', 'Heavy motor vehicle'),
        ('T', 'Two wheeled vehicle'),
        ('O', 'Other'),
    )
    vehicle_type = models.CharField(max_length=1, default='L', choices=vehicle_type_choices)
    
    date = models.DateTimeField(auto_now=True )
    extra_details = models.TextField(max_length=500, null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True, null=True )

    image1 = models.ImageField()
    image2 = models.ImageField(null=True, blank=True)
    image3 = models.ImageField(null=True, blank=True)
    image4 = models.ImageField(null=True, blank=True)
    image5 = models.ImageField(null=True, blank=True)
    image6 = models.ImageField(null=True, blank=True)
    image7 = models.ImageField(null=True, blank=True)
    
    image_count = models.IntegerField(default=1, blank=True)
    view_count = models.IntegerField(default=0, blank=True)

    class Meta:
        ordering = ['-date']

    def __str__(self) -> str:
        return self.vehicle_name
    
    def get_absolute_url(self):
        return reverse('view-offer', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('delete-offer', kwargs={'slug': self.slug})

    def get_edit_url(self):
        return reverse('edit-offer', kwargs={'slug': self.slug})

    def get_enquiry_url(self):
        return reverse('enquire', kwargs={'slug': self.slug})

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, SetPasswordForm
from .models import CustomUser

class CustomUserForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2', 'location', 'about', 'phone_number', 'account_type']

class CustomUserUpdateForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'location', 'about', 'phone_number', 'account_type']

class CustomUserChangePasswordForm(SetPasswordForm):
    class Meta:
        model = CustomUser
        fields = ['password1', 'password2']

class CustomUserDisplayPhotoForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['display_photo',]

accounts/views.py
from datetime import datetime, date
from django.shortcuts import redirect, render
from django.contrib import messages
from django.utils.text import slugify
from .forms import CustomUserForm, CustomUserDisplayPhotoForm, CustomUserUpdateForm, CustomUserChangePasswordForm
from .models import CustomUser, Notification
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required

def account(request, slug):
    context = {
        'new_notifications': Notification.objects.filter(owner=request.user, view_count=0) if request.user.is_authenticated else None,
        'user': CustomUser.objects.get(slug=slug)
    }

    return render(request, 'accounts/account.html', context)

def user_signup(request):
    if request.user.is_authenticated:
        messages.info(request, "You are already logged in as '" + request.user.username + "'. Please logout first to create another account.")
        return redirect('home')

    if request.method == 'POST':
        form = CustomUserForm(request.POST)
    
        if form.is_valid():
            user = form.save()
            user.slug = slugify(user.username + "-" + str(user.id))
            if user.about == "A short description of yourself/your dealership": 
                user.about = ''
            user.save()
            login(request, user)            

            # create relevant notifications
            Notification.objects.create(
                owner = user,
                title = "Getting started guide 1.",
                body = "Welcome to cars.zim {}. Get started by creating your first offer \
                    <a href={% url 'create-offer' %}>Here</a>".format(user.username),
                icon = 'S'
            )
            Notification.objects.create(
                owner = user,
                title = "Getting started guide 2.",
                body = "<a href={}>Upload</a> a display photo and <a href={% url 'user-settings' %}>\
                    tweak your settings</a> to your likeness.".format(user.get_absolute_url()),
                icon = 'S'
            )

            messages.success(request, 'Welcome to cars.zim ' + user.username + ". Your account was created successfully.")
            return redirect(user.get_absolute_url())
        else:
            messages.error(request, form.errors.as_text(), 'danger')

    return render(request, 'accounts/signup.html', {'action': 'Signup'})

def user_login(request):
    if request.user.is_authenticated:
        messages.info(request, "You are already logged in as '" + request.user.username + "'. Logout if you wish to log into another account.")
        return redirect('home')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username=username, password=password)
        if user != None:
            login(request, user)
            messages.success(request, "Welcome back! Logged in as '" + user.username + "'.")
            return redirect(user.get_absolute_url())
        else:
            messages.error(request, "Incorrect password or Username", 'danger')        
    
    return render(request, 'accounts/login.html')

@login_required(login_url='user_login')
def user_logout(request):
    logout(request)
    messages.warning(request, 'You were logged out.')

    return redirect('home')

@login_required(login_url='user_login')
def user_notifications(request):
    notifications = Notification.objects.filter(owner=request.user)
    
    count = 0
    for notification in notifications:
        if notification.view_count > 8:
            notification.delete()
            count += 1
        else:
            notification.view_count += 1
            notification.save()

    context = {
        'notifications': Notification.objects.filter(owner=request.user)
    }

    if count:
        suffix = 's were' if count > 1 else ' was' 
        messages.info(request, f'{count} old notification{suffix} removed.')

    return render(request, 'accounts/notifications.html', context)

@login_required(login_url='user_login')
def change_display_photo(request):
    if request.method == 'POST':
        form = CustomUserDisplayPhotoForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your display photo was updated successfully.')
        else:
            messages.error(request, form.errors.as_text(), 'danger')

    return redirect(request.user.get_absolute_url())

@login_required(login_url='user_login')
def update_profile(request):
    if request.method == 'POST':
        form = CustomUserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            user = form.save()
            user.slug = slugify(user.username + "-" + str(user.id))
            if not user.phone_number: 
                user.notification_inbox = 'E'
            if user.about == "A short description of yourself/your dealership": 
                user.about = ''
            user.save()
            messages.success(request, 'Your account details were updated successfully.')
            return redirect(user.get_absolute_url())
        else:
            messages.error(request, form.errors.as_text(), 'danger')

    return render(request, 'accounts/signup.html', {'action': 'Update account'})

@login_required(login_url='user_login')
def user_settings(request):
    return render(request, 'accounts/settings.html')

@login_required(login_url='user_login')
def update_inbox_settings(request):
    try:
        if request.method == 'POST':
            selected_inbox = request.POST.get('notification_inbox')        
            request.user.notification_inbox = selected_inbox
            request.user.save()

    except:
        messages.error(request, 'Failed to update notification settings', 'danger')
        return redirect('/')

    else:
        messages.success(request, 'Your notification settings were updated successfully.')

    return render(request, 'accounts/settings.html')

@login_required(login_url='user_login')
def change_password(request):
    if request.method == 'POST':
        form = CustomUserChangePasswordForm(request.user, request.POST)
        if form.is_valid():
            logout(request)
            user = form.save()
            login(request, user)
            messages.success(request, 'Password changed successfully.')

            # create relevant notification
            Notification.objects.create(
                owner = request.user,
                title = "Your password was recently changed.",
                body = "Your password was changed on {} at {}. If this was not you, \
                    <a href=''>click here</a> to get a password reset link sent to your email".format(
                            date.today(),
                            datetime.today().time()
                        ),
                icon = 'ET'
            )
        
        else:
            messages.error(request, form.errors.as_text(), 'danger')
            # create relevant notification
            Notification.objects.create(
                owner = request.user,
                title = "There was an attempt to change your password.",
                body = "There was an attempt to change your password \
                        on {} at {}. If this was not you, <a href=''>click here</a> \
                        to get a password reset link sent to your email. \
                        This will logout your account on any device".format(
                            date.today(),
                            datetime.today().time()
                        ),
                icon = 'ET'
            )

    return render(request, 'accounts/settings.html')

accounts/templates/accounts/account.html
{% extends 'app/base.html'%} 
{% load static %} 
{% block title %} {{user.username }} {% endblock title %} 

{% block modals %} 
	{{ block.super }} 
{% endblock modals %} 

{% block offcanvases %} 
	{{ block.super }} 
{% endblock offcanvases%} 

{% block content %}
	<main class="container-fluid my-4">
		<div class="row justify-content-around position-relative">
			<div
				class="col-lg-4 col-xl-3 p-0 profile-sidebar sticky-lg-top shadow rounded"
			>
				<form action="{% url 'change-display-photo' %}" method="post" enctype="multipart/form-data"
					class="profile-images d-flex justify-content-center align-items-center position-relative overflow-hidden"
				>
					{% csrf_token %}

					{% if request.user == user %}
					<a
						class="btn btn-primary shadow-lg position-absolute end-0 bottom-0 m-2"
						onclick="clickNext(this)"
					>
						<i class="bi bi-camera"></i>
					</a>

					<input
						type="file"
						name="display_photo"
						onchange="clickNext(this)"
						class="d-none"
					/>

					<button type="submit" class="d-none"></button>
					{% endif %}

					<h5
						class="account-username shadow-lg position-absolute start-0 bottom-0 p-2 m-0"
					>
						{{ user.username }}
					</h5>

					<img
						src="{{ user.display_photo.url }}"
						alt="display photo"
						class="w-100"
					/>
				</form>

				<div class="account-details p-3">
					{% if request.user == user %}
					<div class="mb-3">
						<a href="{% url 'update-profile' %}" class="btn btn-primary">
							<i class="bi bi-pencil-square"></i
						></a>

						<a href="{% url 'user-settings' %}" class="btn btn-primary">
							<i class="bi bi-gear"></i
						></a>

						<button
							type="button"
							class="btn btn-primary"
							data-bs-toggle="modal"
							data-bs-target="#logoutmodal"
						>
							<i class="bi bi-box-arrow-right"></i>
						</button>
					</div>
					{% endif %}

					<p><i class="bi bi-envelope-fill pe-2"></i>{{ user.email }}</p>

					{% if user.account_type == 'DA' %}
					<p><i class="bi bi-people-fill pe-2"></i>Dealership</p>
					{% else %}
					<p><i class="bi bi-person-fill pe-2"></i>Normal Account</p>
					{% endif %}

					<p>
						<i class="bi bi-geo-alt-fill pe-2"></i>{{ user.location }}
					</p>

					{% if user.phone_number %}
					<p>
						<i class="bi bi-telephone-fill pe-2"></i>
						{{ user.phone_number }}
					</p>
					{% endif %} 
					{% if user.about %}
					<p>{{ user.about }}</p>
					{% endif %}
				</div>
			</div>

			<div class="col-lg-8">
				<h2 class="text-center mt-2">
					Offers - {{ user.offer_set.count }}
				</h2>

				{% if user.offer_set.count != 0 %}
					<div class="container-fluid">
						{% for offer in user.offer_set.all %} 
							{% include 'app/offer_single.html' %} 
						{% endfor %}
					</div>

					<nav aria-label="Page navigation" class="my-5">
						<ul class="pagination justify-content-center">
							<li class="page-item disabled">
								<a class="page-link">Previous</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="#">1</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="#">2</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="#">3</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="#">Next</a>
							</li>
						</ul>
					</nav>
				{% else %}
					{% if user == request.user %}
						<p class="display-5 py-5 my-5 text-center">
							Start Uploading Offers <br>
							<a href="{% url 'create-offer' %}" class="btn text-success"><i class="bi bi-plus-circle fs-1"></i></a>
						</p>
					{% endif %}
				{% endif %}

			</div>
		</div>
	</main>
{% endblock content %} 

{% block footer %} 
	{{ block.super }} 
{% endblock footer %}

accounts/templates/accounts/login.html
{% extends 'app/base.html'%} 
{% load static %} 
{% block title %} Login {% endblock title %} 

{% block modals %} 
	{{ block.super }} 
{% endblock modals %}

{% block content %}
	<main class="p-5">
		<h1 class="display-1 text-center">
			<i class="bi bi-person-circle"></i>
		</h1>

		<h1 class="text-center mb-3">Login</h1>

		<form method="post" class="mx-auto signin-form">
			{% csrf_token %}

			<div class="form-floating mb-3">
				<input
					name="username"
					type="text"
					maxlength="20"
					class="form-control"
					id="floatingInput"
					placeholder="Username"
				/>
				<label for="floatingInput">Username</label>
			</div>

			<div class="form-floating mb-3">
				<input
					name="password"
					type="password"
					class="form-control"
					id="floatingPassword"
					placeholder="Password"
				/>
				<label for="floatingPassword">Password</label>
			</div>

			<div class="d-flex justify-content-between">
				<div>
					<p class="mb-3">
						Don't have an account? <br />
						<a class="normal-link" href="{% url 'user-signup' %}">Signup</a>
					</p>

					<a class="d-block normal-link" onclick="clickNext(this)"
						>Forgot Password</a
					>

					<button
						type="button"
						class="d-none"
						data-bs-toggle="modal"
						data-bs-target="#forgotpasswordmodal"
					></button>
				</div>

				<div>
					<button class="btn btn-primary" type="submit">
						Login
					</button>
				</div>
			</div>
		</form>
	</main>
{% endblock content %} 

{% block footer %}  
{% endblock footer %}

accounts/templates/accounts/notifications.html
{% extends 'app/base.html'%} 
{% load static %} 
{% block title %} Notifications {% endblock title %} 

{% block modals %} 
{% endblock modals %}

{% block offcanvases %} 
{% endblock offcanvases %}

{% block content %}
	<main class="my-5">
		<h1 class="text-center py-2">
			Notifications <i class="bi bi-bell"></i>
		</h1>

		{% if notifications %}
		<div class="container p-2">
			<div
				class="accordion accordion-flush"
				id="notficationAccordion"
			>
				{% for notification in notifications %}
					<div class="accordion-item">
						<h2 class="accordion-header" id="flush-heading{{ forloop.counter }}">
							<button
								class="accordion-button lead collapsed"
								type="button"
								data-bs-toggle="collapse"
								data-bs-target="#flush-collapse{{ forloop.counter }}"
								aria-expanded="false"
								aria-controls="flush-collapse{{ forloop.counter }}"
							>
								<div class="notification-header">
									<h5 class="p-0 m-0 d-flex align-items-center">
										<span>
											<i class="{{ notification.get_icon_display }} pe-1"></i>
											{{ notification.title|capfirst }}
										</span>
										<span class=" ms-md-5 text-success">
											<i class="bi bi-clock me-1"></i>{{ notification.date|date:'SHORT_DATE_FORMAT' }}
										</span>
									</h5>
								</div>
							</button>
						</h2>

						<div
							id="flush-collapse{{ forloop.counter }}"
							class="accordion-collapse collapse px-5"
							aria-labelledby="flush-heading{{ forloop.counter }}"
							data-bs-parent="#notficationAccordion"
						>
							<div class="accordion-body">
								{{ notification.body|capfirst|safe }}
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
		{% else %}
			<h5 class=" p-4 text-center">
				No recent notifications
			</h5>
		{% endif %}
	</main>
{% endblock content %} 

{% block footer %}  
{% endblock footer %}

accounts/templates/accounts/settings.html
{% extends 'app/base.html'%} 
{% load static %} 
{% block title %} Settings {% endblock title %} 

{% block modals %} 
	{{ block.super }}
{% endblock modals %}

{% block offcanvases %}
	{{ block.super }}
{% endblock offcanvases %}

{% block content %}
	<main class="my-5">
		<h1 class="text-center py-2">
			Settings <i class="bi bi-gear"></i>
		</h1>

		<div class="container p-2">
			<div class="accordion accordion-flush" id="settingsAccordion">
				<div class="accordion-item">
					<h2 class="accordion-header" id="flush-headingOne">
						<button
							class="accordion-button lead collapsed"
							type="button"
							data-bs-toggle="collapse"
							data-bs-target="#flush-collapseOne"
							aria-expanded="false"
							aria-controls="flush-collapseOne"
						>
							<div class="notification-header">
								<h5 class="p-0 m-0">
									<i class="bi bi-bell pe-2"></i
									>Notifications
								</h5>
							</div>
						</button>
					</h2>

					<div
						id="flush-collapseOne"
						class="accordion-collapse collapse px-5"
						aria-labelledby="flush-headingOne"
						data-bs-parent="#settingsAccordion"
					>
						<div class="accordion-body">
							<h6>Select how you receive notifications.</h6>

							<form method="post" action="{% url 'update-inbox-settings' %}">
								{% csrf_token %}

								<div class="form-radio py-1">
									<input
										class="form-radio-input"
										type="radio"
										name="notification_inbox"
										value="S"
										id="smsradio"
										{% if not request.user.phone_number %}
											disabled
										{% endif %}

										{% if request.user.notification_inbox == 'S' %}
											checked
										{% endif %}
									/>

									<label
										class="form-radio-label"
										for="smsradio"
									>
										SMS
									</label>

									{% if not request.user.phone_number %}
									<small class="text-success px-3">
										<i class="bi bi-info-circle"></i>
										You'll need to provide your phone
										number.
										<a href="{% url 'update-profile' %}" class="normal-link"
											>edit account details</a
										>
									</small>
									{% endif %}
								</div>

								<div class="form-radio py-1">
									<input
										class="form-radio-input"
										type="radio"
										name="notification_inbox"
										value="E"
										id="emailradio"
										{% if request.user.notification_inbox == 'E' %}
											checked
										{% endif %}
									/>

									<label
										class="form-radio-label"
										for="emailradio"
									>
										Email
									</label>
								</div>
								
								<div class="form-radio py-1">
									<input
										class="form-radio-input"
										type="radio"
										name="notification_inbox"
										value="B"
										id="bothradio"
										{% if request.user.notification_inbox == 'B' %}
											checked
										{% endif %}

										{% if not request.user.phone_number %}
											disabled
										{% endif %}
									/>

									<label
										class="form-radio-label"
										for="bothradio"
									>
										Both
									</label>
								</div>

								<div class="py-2">
									<button
										type="submit"
										class="btn btn-primary"
									>
										Save changes
									</button>
								</div>
							</form>
						</div>
					</div>
				</div>

				<div class="accordion-item">
					<h2 class="accordion-header" id="flush-headingTwo">
						<button
							class="accordion-button lead collapsed"
							type="button"
							data-bs-toggle="collapse"
							data-bs-target="#flush-collapseTwo"
							aria-expanded="false"
							aria-controls="flush-collapseTwo"
						>
							<div class="notification-header">
								<h5 class="p-0 m-0">
									<i class="bi bi-person pe-2"></i>Deactivate your account
								</h5>
							</div>
						</button>
					</h2>

					<div
						id="flush-collapseTwo"
						class="accordion-collapse collapse px-5"
						aria-labelledby="flush-headingTwo"
						data-bs-parent="#settingsAccordion"
					>
						<div class="accordion-body">
							<h6>Deactivate or delete your account.</h6>

							<p class="text-success">
								<i class="bi bi-info-circle pe-1"></i
								>Deactivating your account will temporarily
								remove your offers and profile from view on
								the platform, but nothing will be deleted.
								Your account will be reactivated when you
								log in again.
							</p>

							<div class="py-2">
								<a href="" class="btn btn-dark"
									>Deactivate</a
								>
								<a href="" class="btn btn-outline-dark mx-2"
									>Delete</a
								>
							</div>
						</div>
					</div>
				</div>

				<div class="accordion-item">
					<h2 class="accordion-header" id="flush-heading3">
						<button
							class="accordion-button lead collapsed"
							type="button"
							data-bs-toggle="collapse"
							data-bs-target="#flush-collapse3"
							aria-expanded="false"
							aria-controls="flush-collapse3"
						>
							<div class="notification-header">
								<h5 class="p-0 m-0">
									<i class="bi bi-lock pe-2"></i
									>Change Password
								</h5>
							</div>
						</button>
					</h2>

					<div
						id="flush-collapse3"
						class="accordion-collapse collapse px-5"
						aria-labelledby="flush-heading3"
						data-bs-parent="#settingsAccordion"
					>
						<div class="accordion-body">
							<form method="post" action="{% url 'change-password' %}">
								{% csrf_token %}
								
								<div class="form-floating mb-3 w-fit">
									<input
										name="new_password1"
										type="password"
										class="form-control w-fit"
										id="password1"
										placeholder="New Password"
									/>
									<label for="password1">New Password</label>
								</div>

								<div class="form-floating mb-3 w-fit">
									<input
										name="new_password2"
										type="password"
										class="form-control w-fit"
										id="password2"
										placeholder="Confirm New Password"
									/>
									<label for="password2">Confirm New Password</label>
								</div>

								<div class="py-2">
									<button
										type="submit"
										class="btn btn-primary"
									>
										Change
									</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</main>
{% endblock content %} 

{% block footer %}  
{% endblock footer %}